name: Prettier Check

on:
  push:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Prettier
        uses: creyD/prettier_action@v4
        with:
          prettier_options: --write .
